version: "3.1"

services:
  db:
    container_name: db_myFinances
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: myFinances
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./data:/var/lib/mysql"

  db_tests:
    container_name: db_myFinances_tests
    image: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: myFinances_tests
      MYSQL_ROOT_PASSWORD: root
